### ISSUE TITLE
Upright bandsaw - new blade

### ISSUE THREAD

**Issue by ZebBerg** [eugenemakerspace/shoptools#11]
The blade broke for the large upright woodworking bandsaw and needs a replacement.
The bandsaw has been moved next to the CNC table for now.

**Comment by esden** [comment]
As this is a consumable. If you are a bandsaw user, I would recommend that you either donate a new blade, or come together with other bandsaw users to buy a new replacement blade. This is the best way to get the tool back up and running.

**Comment by zebragrrl** [comment]
**_Please mark issue as resolved._** 
 
---
**sfoster** — Today at 3:20 PM
> Ok both bandsaws back in action. There are 2 more finer tooth blades for the little delta saw on the shelf above and behind it.
> I'm also putting a 1/2 sanding belt for the larger craftsman saw up there
> The craftsman saw works great. It is a little shakey but cuts well, plenty of power
